---
- name: Error Handling
  hosts: all
  tasks: 
    - block:
        - name: Install tree using apt
          apt:
            name: tree
            state: present
            update_cache: yes
      rescue:
        - name: Install tre using yum
          yum:
            name: tree
            state: present
            update_cache: yes
      always: 
         - name: Display success info
           debug:
             msg: "tree installation successfull"

...
