---
- name: check if folder f1 is present if not create a file f1
  hosts: all
  tasks: 
     - name: check for folder f1
       stat:
         path: /home/ubuntu/f1
       register: a
     - name: Display output of the above module
       debug: 
          var: a
...
