---
- name: setup of jenkins and required s/w's
  hosts: jenkins
  tasks: 
    - name: install dependent s/w's
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items: 
          - {a: openjdk-11-jdk,b: yes} 
          - {a: git,b: no}
          - {a: maven,b: no}
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.361.3/jenkins.war
        dest: /home/ubuntu
          

