---
- name: Implementing handlers
  hosts: all
  tasks: 
    - name: Install apache2
      apt:
        name: apache2
        state: present
        
    - name: Edit the index.html file
      copy: 
        content: "welcome to intelliqit" 
        dest: /var/www/html/index.html
      notify: Restart apache

- handlers:
        - name: Restart apache
          service:
              name: apache2
              state: restarted
